// Cleans the raw ESMA CASP register CSV into a tidy src/data/casps.json.
// Run: npm run data   (or: node scripts/clean-data.mjs)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { detectServices } from "../src/lib/services.js";
import { normalizeCountry } from "../src/lib/countries.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SRC_CSV = join(ROOT, "CASPS list.csv");
const OUT_JSON = join(ROOT, "src", "data", "casps.json");

// National company-register numbers (GLEIF entity.registeredAs), keyed by LEI.
// Generated by `npm run register-numbers` (scripts/fetch-register-numbers.mjs);
// re-run that script after a data refresh so newly added CASPs get resolved.
// Empty fallback lets `npm run data` still work before that script has ever
// been run (e.g. a fresh checkout).
let REGISTER_NUMBERS = {};
try {
  REGISTER_NUMBERS = JSON.parse(
    readFileSync(join(ROOT, "src", "data", "register-numbers.json"), "utf8"),
  );
} catch {
  // not generated yet; every companyRegisterNumber below stays null.
}

// --- Minimal RFC 4180 CSV parser (handles quotes, escaped quotes, newlines) ---
function parseCSV(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else inQuotes = false;
      } else field += c;
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\r") {
      // ignore, handled by \n
    } else if (c === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else field += c;
  }
  if (field.length || row.length) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

// --- Fix the handful of corrupted (mojibake) characters in the source ---
const R = "�"; // replacement character
function fixEncoding(s) {
  if (!s) return s;
  return s
    .split(`Stra${R}e`).join("Straße")
    .split(`L${R}w`).join("Löw")
    .split(`${R}Kraken${R}`).join("“Kraken”")
    .split(R).join(""); // drop any remaining stray replacement chars
}

function clean(s) {
  if (s == null) return "";
  return fixEncoding(String(s))
    .replace(/\s+/g, " ")
    .trim();
}

// dd/mm/yyyy -> { raw, iso }
function parseDate(s) {
  const raw = clean(s);
  const m = raw.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (!m) return { raw, iso: null };
  const [, d, mo, y] = m;
  const iso = `${y}-${mo.padStart(2, "0")}-${d.padStart(2, "0")}`;
  return { raw, iso };
}

function parseCountries(s) {
  if (!s) return [];
  const tokens = s.split(/\||\sI\s|\/|,/g);
  const out = new Set();
  for (const t of tokens) {
    const cc = normalizeCountry(t);
    if (cc) out.add(cc);
  }
  return [...out].sort();
}

function slugify(s) {
  return s
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// Known-good websites for records whose ESMA row carries no usable URL in any
// column (the source put a page title there instead), OR whose only URL is a
// typo that resolves to nothing (checked manually). Keyed by LEI for stability
// across data refreshes. Only add unambiguous, easily verified official sites.
// Takes priority over pickUrl() below, since a wrong-but-domain-shaped URL from
// the source would otherwise win.
const WEBSITE_BY_LEI = {
  "529900JB9XYZ8E87N345": "https://n26.com", // N26 Bank SE
  "851WYGNLUQLFZBSYGB56": "https://www.commerzbank.com", // Commerzbank AG
  // Source col 7 is "www-vrbank-obb-so.de" (dashes instead of dots; does not
  // resolve). Real site verified 2026-08-03: https://www.vrbank-obb-so.de
  "5299005O2LPWV9IP2Z21": "https://www.vrbank-obb-so.de", // Volksbank Raiffeisenbank Oberbayern Suedost eG
};

// Override the display name when the source commercial-name field is a junk list
// of brands/domains rather than a single brand. Keyed by LEI.
const NAME_BY_LEI = {
  // commercial name is "Change, Change Invest, getchange.com, ChangePro, ..."
  "7245009PUAT6U71IXZ51": "Change", // Change Securities B.V.
};

// Brand / "also known as" info for entities that hold the ESMA-registered CASP
// licence under one (legal) name but trade publicly under a parent-group brand.
// The licence belongs to the legal entity (`name`/`legalName`); `aka` is the brand
// it also operates under, surfaced so both names appear and are searchable. Keyed
// by LEI for stability across data refreshes. Only add when independently verified.
const BRAND_BY_LEI = {
  // PAYTOP SAS is the French CASP entity of the Triple-A group ("Triple-A EU").
  // Verified via Triple-A's own legal disclosure (triple-a.io) + AMF white list.
  "969500VA4A8CRCS2N988": {
    aka: "Triple-A",
    brandSite: "triple-a.io",
    // Rendered as raw HTML in the drawer (author-controlled, not user input), so the
    // two addresses are clickable. Keep links target=_blank rel="noopener nofollow".
    noteHtml:
      '<a href="https://www.triple-a.io/" target="_blank" rel="noopener nofollow">Triple-A (triple-a.io)</a> is the owner of <a href="https://www.paytop.com" target="_blank" rel="noopener nofollow">Paytop SAS (www.paytop.com)</a>, the legal entity that holds this CASP authorisation.',
  },
};

// The source CSV truncates this LEI to 19 characters (fails the ISO 17442
// checksum); the correct 20-char LEI was confirmed via GLEIF's own
// legal-name search on 2026-08-12. Keyed by the WRONG (source) value, since
// that's what we're correcting away from.
const LEI_FIX = {
  "724500YJVIN0Q94ZZG5": "724500YJVIN0Q94ZZG58", // WEB3 Technology B.V. (Ari10)
};

// Whether (and how) each home state's regulator assigns its OWN reference
// number for a MiCA authorisation - a THIRD identifier, distinct from both
// the LEI (global, ESMA-published) and the GLEIF-sourced company register
// number (national commercial-register ID, e.g. Austrian Firmenbuch).
// MiCA (Art. 109) mandates only the LEI in the ESMA register, so anything
// beyond that is a purely national artifact with no shared format. Researched
// per-country 2026-08-12 (full sourcing in the casp-license-numbers-research
// memory); re-check if a country not listed here ever gains a CASP.
//   'register'  - the regulator publishes a register/list where the entity
//                 has an explicit reference number (format varies wildly).
//   'informal'  - a reference exists but only per licensing decision (e.g. a
//                 resolution number), not in a public, browsable register.
//   'none'      - confirmed: no separate number exists anywhere; the entity
//                 is identified only by its LEI and company register number.
export const NCA_NUMBER_POLICY = {
  DE: { status: "register", label: "BaFin-ID" },
  FR: { status: "register", label: "AMF authorisation/notification number" },
  NL: { status: "register", label: "AFM authorisation number" },
  CY: { status: "register", label: "CySEC licence number" },
  // MFSA's Financial Services Register shows only a short identification
  // code (e.g. "OEUR"), not a verified numbering scheme.
  MT: { status: "informal" },
  // CNMV's PSC list carries no number of any kind: name + tax ID only.
  ES: { status: "none" },
  LU: { status: "register", label: "CSSF licence number" },
  IE: { status: "register", label: "Central Bank of Ireland reference (C-number)" },
  // FMA authorisations are announced individually; its MiCAR register app
  // exists but had zero entries as of 2026-08-12.
  LI: { status: "informal" },
  // FMA assigns no number at all; only the Firmenbuch commercial-register
  // number (below, via GLEIF) identifies the entity.
  AT: { status: "none" },
  // CNB's JERRS register keys entities by IČO (business ID) only.
  CZ: { status: "none" },
  LV: { status: "register", label: "Latvijas Banka licence number" },
  // No Italian national register exists; Consob issues per-decision
  // "delibera" numbers, not a browsable register entry.
  IT: { status: "informal" },
  DK: { status: "register", label: "Finanstilsynet reference (FT-nr.)" },
  HR: { status: "register", label: "HANFA register number" },
  LT: { status: "register", label: "Lietuvos bankas licence number" },
  NO: { status: "register", label: "Finanstilsynet registry ID" },
  // NBS register keys entities by IČO (business ID) only.
  SK: { status: "none" },
  // FIN-FSA register keys entities by Y-tunnus (business ID) only.
  FI: { status: "none" },
  BG: { status: "register", label: "FSC decision number" },
  EE: { status: "register", label: "Finantsinspektsioon licence number" },
  // Only per-decision ATVP case references exist, no public register.
  SI: { status: "informal" },
  // FSMA's public CASP lists were empty for both Belgian entities (NBB-side
  // Art. 60 notifications) as of 2026-08-12; no number published anywhere.
  BE: { status: "none" },
  // Central Bank of Iceland cites only the entity's kennitala (national ID).
  IS: { status: "none" },
  // Banco de Portugal shows only the entity's tax number (NIPC).
  PT: { status: "none" },
  SE: { status: "register", label: "Finansinspektionen institution number" },
};

// Verified regulator reference numbers, keyed by LEI (stable across
// re-slugging). Sourced directly from each regulator's own register/API/page
// (never a third-party mirror) - see the casp-license-numbers-research memory
// for full citations. This is a curated STARTING set (~15% of entries, the
// ones confirmed during the 2026-08-12 research pass), filled in
// incrementally over time, same convention as WEBSITE_BY_LEI/BRAND_BY_LEI
// above. An entity without an entry here still gets its NCA_NUMBER_POLICY
// status shown, so the UI never implies a number doesn't exist just because
// we haven't collected it yet.
export const NCA_NUMBER_BY_LEI = {
  // Luxembourg - CSSF Search Entities public API (full 13/13, live 2026-08-12)
  "213800W1NGBLERUS6M39": "N00000001", // Banking Circle S.A.
  "549300OL514RA0SXJJ44": "N00000002", // Clearstream Banking S.A.
  "549300XIBGTJ0PLIEO72": "N00000003", // Bitstamp Europe S.A.
  "984500F14CA4571AAC11": "N00000004", // Coinbase Luxembourg S.A.
  "213800K35A9YPYDQKB81": "N00000006", // Zodia Custody (Europe) S.A.
  "969500OA6NVZB5BXAB29": "N00000007", // B2C2 Europe Sarl
  "549300M2IHOB9P5WE714": "N00000008", // Swissquote Bank Europe SA
  "984500BA521C5EMR1D63": "N00000009", // STOKR S.A.
  "213800HAR45C9K18O294": "N00000010", // Standard Chartered Luxembourg S.A.
  "984500D4465EFA89EF38": "N00000011", // bitFlyer EUROPE S.A.
  "254900MVWQXMF77YZP65": "N00000012", // Bridge Building S.A.
  "984500CFB88366E9B834": "N00000013", // CPS Europe S.A.
  "2549000KEHDV2LWRRZ45": "N00000014", // Ripple Payments Europe S.A.
  // Netherlands - AFM register-cryptopartijen.xlsx, FULL register (official,
  // live 2026-08-12, 29/29 NL entries matched by LEI - complete coverage).
  "699400TPXCI7R4A0NG65": "41000007", // Acheron Europe B.V.
  "724500T7PFN30PF3ZQ87": "41000012", // Amdax B.V.
  "894500KQLQQYOD1PPX55": "41000005", // AvianLabs Netherlands B.V.
  "724500H1WRSMD7CAS549": "41000013", // Bitmymoney B.V.
  "7245001BEJ6U6AUU1S58": "41000024", // Bitonic B.V.
  "724500F2THLY5MHEIM78": "41000045", // BitPay B.V.
  "7245009PN18D4I1TKJ50": "41000003", // BitStaete B.V.
  "724500MX2WBKDJP9HE56": "41000010", // Bitvavo B.V.
  "724500J6RZI9SE1AAP41": "41000029", // Blockrise Capital B.V.
  "724500Z8JCXSX3351I94": "41000020", // BLOX B.V.
  "724500C4D3LQAKCEZ198": "41000009", // BTC Direct Europe B.V.
  "7245009PUAT6U71IXZ51": "41000082", // Change Securities B.V.
  "724500EAW1MTCM9M1X68": "41000085", // ClearBank Europe N.V.
  "724500DMUDFJZNYNEF35": "41000019", // Coinmerce B.V.
  "7245002DD3GNFXPGPP93": "41000072", // D2X Group N.V.
  "894500ZVOL3A9LO8LN34": "41000018", // Decubate B.V.
  "724500QZRWKCU8D2L569": "41000071", // Digital Currency Services B.V.
  "69940000HAL9ODW3IMO22": "41000017", // EU Internet Ventures B.V.
  "724500GVWT7QULV8CR59": "41000041", // Fiat Republic Netherlands B.V.
  "724500UI8UD7HKGVJX65": "41000015", // Finst B.V.
  "549300OOZDNZ3F2XJW21": "41000008", // Hidden Road Partners CIV NL B.V.
  "724500BUG93MDFGYQG03": "41000025", // Monflo B.V.
  "254900KXWAZ3B1340G26": "41000002", // MoonPay Europe B.V.
  "984500AA963ED2BA8460": "41000034", // One Trading Exchange B.V.
  "7245009PWS7YLG3JPF78": "41000035", // Vivid Money B.V.
  "724500YJVIN0Q94ZZG58": "41000022", // WEB3 Technology B.V. (Ari10)
  "894500CUU8Y0ZBG8DX95": "41000091", // Webull Securities (Europe) B.V.
  "724500B2I1LR33CAWG54": "41000001", // Zebedee Europe B.V.
  "724500G7QSOMFR1GQA47": "41000042", // zerohash europe B.V.
  // France - AMF white list official CSV export (data.gouv.fr, live 2026-08-12,
  // 34/35 FR entities matched by LEI - the one gap, APLO SAS, shares its LEI
  // with FLOWDESK EUROPE SAS by a known ESMA source error, see
  // NCA_NUMBER_BY_SLUG below for how that one is resolved instead).
  "969500ULPB59U51BG334": "A2026-021", // ALPHACAP DIGITAL ASSETS SAS
  "969500A4IPKVUBH3CA90": "N2025-004", // BANQUE DELUBAC ET CIE
  "894500RKZ3TVTPIF7V84": "A2025-003", // BITSTACK DIGITAL ASSETS SAS
  "9695000VFDEG5Z4JIY48": "A2026-029", // BLOCKCHAIN PROCESS SECURITY (B.P.S.) SAS
  "969500PZJWT3TD1SUI59": "A2026-011", // BLOCKNODES SAS
  "96950082Z6KUVA6TW686": "N2026-006", // Bpifrance Investissement
  "96950023SCR9X9F3L662": "N2025-001", // CACEIS BANK
  "969500OYUDADGZKCR583": "N2026-005", // CIRCLE INTERNET FINANCIAL EUROPE SAS
  "969500E5GFHK2RKF8251": "A2026-013", // COINHOUSE SAS
  "969500DBF3ZL9U0KUA51": "N2025-002", // COINSHARES ASSET MANAGEMENT
  "894500R5KSX3ZKIHSA46": "A2025-008", // COMETH SAS
  "254900XTUI35BGIBXP21": "A2025-001", // DEBLOCK SAS
  "969500QH6WD4FO79B261": "A2026-012", // DESKOIN SAS
  "969500RQH18PU24DM081": "A2026-026 / N2026-008", // FINARY SAS
  "969500PTJJZTCE0I3B60": "A2025-005", // FINCTEK UE SAS
  "969500A0DYUNF5NX9R84": "A2026-009", // FIPTO PI SAS
  "984500AB011S3AEF6706": "A2026-022", // FLOWDESK EUROPE SAS
  "894500LM6DICD790FQ34": "A2025-002", // GOin SAS
  "969500TD4VXAOPXPVW02": "A2026-010", // HEXARQ SAS
  "9695005CVRZDK63ZST85": "A2026-024", // ICEBLOCK SAS
  "9845001BAFC53ODN8C90": "A2026-017", // KEYROCK FR SAS
  "969500O878F3MGJCYV50": "A2026-019", // LEONOD SARL
  "969500USEY22T9ZZRQ98": "A2026-025", // MEREAU FINANCE SAS
  "969500UJSWU20FEXQ504": "A2026-020", // MERIA SAS
  "969500PQYLQG3CSJ5041": "A2025-004", // METAL GEAR SAS
  "969500D241WXU9J7MI33": "A2026-018", // PAYMIUM SAS
  "969500VA4A8CRCS2N988": "A2026-015", // PAYTOP SAS
  "969500CMLNBIVUUD9A09": "A2026-014", // QWARKS SAS
  "529900X4PRL0DZNPT990": "N2026-007", // RCUBE ASSET MANAGEMENT
  "9695003EKRFOMYXJQL11": "A2025-006", // RELAI EU SASU
  "969500FUWSKQEO5J7H72": "A2026-016", // RUFIJI CAPITAL SAS
  "9695001LQMTTVPIIQI05": "A2026-028 / N2026-009", // SHARES FINANCIAL ASSETS SAS
  "969500FX8K40ZDW4F377": "A2025-007 / N2025-003", // SOCIETE GENERALE - FORGE
  "213800RF9FDNJ92AE175": "A2026-027", // WOORTON SAS
  // Cyprus - CySEC MiCAR entity pages (official, live 2026-08-12)
  "213800GIFQMSV7HROS23": "109/10", // eToro (Europe) Ltd
  "9845009846V10FGD4840": "023/26", // Brilliantscope Trading Limited (tothemoon)
  // Germany - BaFin company database (official, live 2026-08-12)
  "5299009IFX1XTKDY4568": "10150368", // Trade Republic Bank GmbH
  "0W2PZJM8XOY22M4GG883": "10100426", // DekaBank Deutsche Girozentrale
  "529900YERL5TV5YJCR45": "10164769", // JT Technologies GmbH (justTRADE)
  // Ireland - Central Bank of Ireland official register (live 2026-08-12)
  "254900641D8KNHUZYX24": "C468360", // Payward Europe Solutions Limited (Kraken)
  "9845003D98SCC2851458": "C559106", // Payward Global Solutions Limited (Kraken)
  // Denmark - Finanstilsynet virksomhedsregister API (official, live 2026-08-12,
  // 7/7 DK entities matched - complete coverage; all FT-nr. fall in one tight
  // 10900-10909 block, cross-confirming the search+detail lookup).
  "9845009Q9DDAE03FDE38": "10907", // Coinify ApS
  "984500A43E7FFC73CR76": "10908", // Januar ApS
  "9845003F777K7DFF4E96": "10909", // SafeLynx Technologies ApS
  "254900TM3KOYH0SY8V19": "10901", // GC Exchange A/S
  "984500DD714F66B77454": "10900", // Lunar Block A/S
  "98450010C0CB6A4E8A79": "10905", // Northstake ApS
  "9845000E4A7414709361": "10902", // Penning Financial Services ApS
  // Norway - Finanstilsynet registry search API (official, live 2026-08-12)
  "636700PFX3CY9R033H73": "221791", // Bare Bitcoin AS
  "5493004WNVZP9EMYI834": "201280", // Norwegian Block Exchange AS (NBX)
  // Lithuania - Lietuvos bankas entity pages (official, live 2026-08-12)
  "254900GTP4UXQO1UMI36": "LB002294", // Robinhood Europe UAB
  "6488907MV9XAA08E4E40": "LB002323 / LB002324", // UAB "Decentralized" (Coingate)
  // Croatia - HANFA register XML export (official, live 2026-08-12; the
  // export lists exactly these 4 entities - complete coverage of the
  // HANFA-supervised side. HR's other 2 CASPs, incl. HPB, are supervised by
  // the Croatian National Bank, which has no public list - see NCA_NUMBER_POLICY).
  "747800R015JVW1T4WZ71": "R30483", // ELECTROCOIN Ltd for services
  "9845006A6CAABE4C0347": "R102212", // Bitblock Ltd. for Services (Kriptomat)
  "984500NB7D12BC5B4A79": "R101065", // DIGITAL ASSETS ... (Bitcoin Store)
  "254900S52YR70F0BK713": "R118357", // WHITE TECH ... for services
  // Bulgaria - FSC register (official, live 2026-08-12)
  "984500FBAE2EDEF1C317": "499-ДУКА", // Altcoins BG EOOD
  "8755007GZKOS1VJ6BZ82": "500-ДУКА", // Digital Assist OOD
  "64882N0ABXS71817AI18": "276-ДУКА", // Belayer OOD
  // Sweden - Finansinspektionen foretagsregistret (official, live 2026-08-12)
  "894500QKMN1PCG2V7U40": "55632", // Safello AB
  // Latvia - Latvijas Banka market-participant profiles (official, live 2026-08-12)
  "259400JCJJ78A4ZCXP93": "27-55/2026/13", // SIA AlphaRoute
  "984500856AF4DF5FAT57": "27-55/2025/7", // AS TWINO Investments
};

// Same regulator number as above, but keyed by SLUG instead of LEI - needed
// for the ONE case where two DIFFERENT French entities share one (erroneous)
// LEI in ESMA's own CSV (see the "Duplicate register rows merged" bullet
// above): APLO SAS's real LEI (per AMF's own CSV, which does distinguish the
// two) is 969500YKHZ31GZ7AAU02, but ESMA's CASPS.csv instead gives it
// FLOWDESK EUROPE SAS's LEI (984500AB011S3AEF6706). Keying APLO's number by
// that shared LEI would silently overwrite/collide with FLOWDESK's own
// (correct) entry above, so it must be looked up by slug instead. Checked
// FIRST in the per-item loop, before NCA_NUMBER_BY_LEI.
export const NCA_NUMBER_BY_SLUG = {
  aplo: "A2026-023", // APLO SAS - AMF CSV, live 2026-08-12
};

// Same LEI-collision problem, but for the GLEIF-sourced company register
// number: APLO's shared (wrong) LEI resolves to FLOWDESK's French RCS via
// GLEIF/register-numbers.json, so APLO needs its own override here too.
// Confirmed via the same AMF CSV row (which lists APLO's real RCS despite
// ESMA's LEI mix-up).
export const COMPANY_REGISTER_BY_SLUG = {
  aplo: { number: "878929405", registerName: "Register of Companies (Sirene)", country: "FR" },
};

// Looks like a real web address (has a dot-separated host with a TLD).
const looksLikeDomain = (s) =>
  /^([a-z0-9-]+\.)+[a-z]{2,}(\/.*)?$/i.test(s) && !/^\d+(\.\d+)*$/.test(s);

function pickUrl(...candidates) {
  for (const raw of candidates) {
    // The source may pack several addresses on one line (newlines / "|" / spaces).
    const tokens = clean(raw)
      .replace(/https?\.\/\//gi, "https://") // fix "https.//" typo
      .split(/[\s|]+/)
      .filter(Boolean);
    for (const tok of tokens) {
      const stripped = tok.replace(/^https?:\/\//i, "").replace(/\/+$/, "");
      if (looksLikeDomain(stripped)) {
        return /^https?:\/\//i.test(tok) ? `https://${stripped}` : `https://${stripped}`;
      }
    }
  }
  return "";
}

function normalizeWebsite(primary, secondary, lei) {
  // A manually-verified override always wins (handles both "no usable URL" and
  // "URL is a resolvable-looking but wrong domain" cases); otherwise fall back
  // to the real URL from the primary website column, then the platform column.
  let href = WEBSITE_BY_LEI[lei] || pickUrl(primary, secondary) || "";
  if (!href) return { display: "", href: "" };
  const display = href.replace(/^https?:\/\//i, "").replace(/\/+$/, "");
  return { display, href };
}

// --- Main ---
const raw = readFileSync(SRC_CSV, "utf8").replace(/^﻿/, "");
const rows = parseCSV(raw);
const header = rows[0];
console.log(`Parsed ${rows.length - 1} raw rows, ${header.length} columns.`);

const usedSlugs = new Map();
function uniqueSlug(base, homeState) {
  let slug = base || "casp";
  if (usedSlugs.has(slug)) {
    const alt = `${base}-${(homeState || "").toLowerCase()}`;
    slug = usedSlugs.has(alt) ? `${alt}-${usedSlugs.get(slug) + 1}` : alt;
  }
  usedSlugs.set(base, (usedSlugs.get(base) || 0) + 1);
  if (usedSlugs.has(slug) && slug !== base) {
    usedSlugs.set(slug, (usedSlugs.get(slug) || 0) + 1);
  }
  return slug;
}

const parsed = [];
for (let i = 1; i < rows.length; i++) {
  const r = rows[i];
  if (!r || r.every((c) => !clean(c))) continue;

  const leiRaw = clean(r[3]);
  const lei = LEI_FIX[leiRaw] || leiRaw;
  const legalName = clean(r[2]);
  const commercial = clean(r[5]);
  const name = NAME_BY_LEI[lei] || commercial || legalName;
  if (!name) continue;

  const homeState = normalizeCountry(r[1]) || clean(r[1]).toUpperCase();
  const website = normalizeWebsite(r[7], r[8], lei);
  const auth = parseDate(r[9]);
  const end = parseDate(r[10]);
  const update = parseDate(r[14]);
  const brand = BRAND_BY_LEI[lei];

  parsed.push({
    slug: null, // assigned after duplicate rows are merged
    name,
    legalName,
    ...(brand?.aka ? { aka: brand.aka } : {}),
    ...(brand?.brandSite ? { brandSite: brand.brandSite } : {}),
    ...(brand?.noteHtml ? { brandNoteHtml: brand.noteHtml } : {}),
    authority: clean(r[0]),
    homeState,
    lei,
    leiCountry: clean(r[4]).toUpperCase(),
    address: clean(r[6]),
    website: website.display,
    websiteHref: website.href,
    services: detectServices(r[11] || ""),
    countries: parseCountries(r[12] || ""),
    authDate: auth.iso,
    authDateRaw: auth.raw,
    endDate: end.iso,
    comments: clean(r[13]),
    lastUpdate: update.iso,
    lastUpdateRaw: update.raw,
  });
}

// --- Merge duplicate register rows for the SAME entity (same LEI + same legal
// name). ESMA lists a second row when an authorisation is extended with new
// services (DekaBank, EUWAX) or plain-duplicates a row (NAGA X). Keyed on LEI
// AND legal name: different companies that share an LEI by source error
// (APLO SAS / FLOWDESK EUROPE SAS) must stay separate entries.
const byEntity = new Map();
const items = [];
for (const it of parsed) {
  const key = it.lei ? `${it.lei}|${it.legalName.toLowerCase()}` : null;
  const prev = key ? byEntity.get(key) : null;
  if (!prev) {
    if (key) byEntity.set(key, it);
    items.push(it);
    continue;
  }
  prev.services = [...new Set([...prev.services, ...it.services])].sort();
  prev.countries = [...new Set([...prev.countries, ...it.countries])].sort();
  // First authorisation date, latest register update.
  if (it.authDate && (!prev.authDate || it.authDate < prev.authDate)) {
    prev.authDate = it.authDate;
    prev.authDateRaw = it.authDateRaw;
  }
  if (it.lastUpdate && (!prev.lastUpdate || it.lastUpdate > prev.lastUpdate)) {
    prev.lastUpdate = it.lastUpdate;
    prev.lastUpdateRaw = it.lastUpdateRaw;
  }
  // The entity stays active if ANY of its rows is still active (no end date).
  prev.endDate =
    prev.endDate && it.endDate
      ? (it.endDate > prev.endDate ? it.endDate : prev.endDate)
      : null;
  if (it.comments && !prev.comments.includes(it.comments)) {
    prev.comments = prev.comments ? `${prev.comments}; ${it.comments}` : it.comments;
  }
  for (const k of ["address", "website", "websiteHref", "leiCountry"]) {
    if (!prev[k] && it[k]) prev[k] = it[k];
  }
  console.log(`Merged duplicate register row: ${prev.legalName} (LEI ${prev.lei}).`);
}

// Slugs are assigned in source-row order (post-merge), so existing slugs of
// non-merged entries are unaffected. The three "other identifier" fields are
// computed here too (once per final deduped entity, not per raw row): LEI
// and homeState are stable through the merge, so this is equivalent to doing
// it earlier but avoids redundant lookups on rows that get merged away.
for (const it of items) {
  it.slug = uniqueSlug(slugify(it.name), it.homeState);

  const regOverride = COMPANY_REGISTER_BY_SLUG[it.slug];
  const regNum = REGISTER_NUMBERS[it.lei];
  it.companyRegisterNumber = regOverride?.number ?? regNum?.number ?? null;
  it.companyRegisterName = regOverride?.registerName ?? regNum?.registerName ?? null;
  it.companyRegisterCountry = regOverride?.country ?? regNum?.jurisdiction ?? null;

  const ncaPolicy = NCA_NUMBER_POLICY[it.homeState] || { status: "unknown" };
  it.ncaNumberStatus = ncaPolicy.status;
  it.ncaNumber = NCA_NUMBER_BY_SLUG[it.slug] || NCA_NUMBER_BY_LEI[it.lei] || null;
  it.ncaNumberLabel = it.ncaNumber ? ncaPolicy.label || null : null;
}

items.sort((a, b) => a.name.localeCompare(b.name, "en"));

const lastDataUpdate = items
  .map((i) => i.lastUpdate)
  .filter(Boolean)
  .sort()
  .at(-1);

const out = {
  generatedAt: new Date().toISOString(),
  source:
    "https://www.esma.europa.eu/esmas-activities/digital-finance-and-innovation/markets-crypto-assets-regulation-mica",
  lastDataUpdate,
  count: items.length,
  items,
};

writeFileSync(OUT_JSON, JSON.stringify(out, null, 2), "utf8");
console.log(`Wrote ${items.length} CASPs -> ${OUT_JSON}`);
console.log(`Latest data update in source: ${lastDataUpdate}`);
const noServices = items.filter((i) => i.services.length === 0).length;
const noCountries = items.filter((i) => i.countries.length === 0).length;
console.log(`Records with no detected services: ${noServices}`);
console.log(`Records with no passporting countries: ${noCountries}`);
